### ISSUE TITLE
Eufy Floodlight Cam 2K T8422 Device no longer Controllable via Home Assistant 

### ISSUE THREAD

**Issue by Brembo427** [fuatakgun/eufy_security#1028]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

Camera is present and all exposed in HA, Can change setting within Eufy APP and HA will reflect the changes, But can no longer change anything via HA. For example, I cannot change guard modes or even toggle on or off the spotlight. Sometime rebooting HA restores control breifly but then stops again. have tried resetting the camera with no success. all over devices on my eufy system work perfectly.  

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to below fields;
- Home Assistant Installation Type: Core
- Home Assistant Core Version: 2023.11.3
- Eufy Security Add-on Version: 1.7.1
- Eufy Security Integration Version: 1.7.7

Hardware Information;
- Camera Model: T8422

- Live Streaming Protocol (RTSP/P2P): 

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624) - Without this, I will automatically resolve this issue
  

- Logs from Eufy Security Add-on (either from Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging required? (Yes/No):

**Additional context**

Add any other context about the problem goes here. Mainly, share everything as log files and use screenshots as last resort.

**Comment by fuatakgun** [comment]
there is a connection issue between add-on and your physical device, it is most probably network related but I cannot do anything about it as we are just sending the request to the device but it does not reach or not acknowledged by it.

**Comment by albuchan** [comment]
I know this was closed as completed - as above related to network issues - but I am struggling to accept that since other functions work and the cameras are specifically reachable. I have tried many things including moving HA from a QNAP based docker container to running currently on a rpi with HassOS. Nothing changed. So I would be interested in understand how to further investigate a network issue. However - I am pasting here a workaround for my automations. Instead of using changing Motion Detection On or Off from the relevant device switch I CAN create new guard modes using the app on the phone. On HA this appears as "custom1" which is basically with a mode with motion OFF and  "custom2" as with motion ON.  I edited the automation actions to change the guard mode options to either custom1 or custom2. This works, but again makes me wonder then if the issue is truly network related (or this would not work either !) .

**Comment by mariomaz87** [comment]
I'm having a similar issue and I couldn't find a workaround. I have an automation where I use the start RTSP command and then take a screenshot. It worked flawlessly until 2 days ago. Now when I send the RTSP on command the camera does not start the streaming and in eufy-ws docker log I have:

2024-05-28 13:46:34.284	WARN	eufy-security-ws:eufy-security-client	[p2p] [P2PClientProtocol._sendCommand] Command aged out from send queue for station XXX {

  commandType: 1144,

  nestedCommandType: undefined,

  channel: 255,

  ageing: 5402094,

  maxAgeing: 120000

}

I'm investigating it and I will update this ticket if I have news.
