### ISSUE TITLE
Support for Eufy 2K wired doorbell

### ISSUE THREAD

**Issue by StonyManager** [fuatakgun/eufy_security#1038]
I have followed the instructions for installation and configuration to the best of my knowledge. I already have a Kasa cam and 4 Lorex cams working (display on the dashboard), but the Eufy 2k wired doorbell is eluding me. 
- Eufy-security-ws installed and configured
- go2rtc installed and configured
- webRTC also installed and configured for other cameras
- This may be as simple as I don't know how to setup the camera on the dashboard. Copy your setup from the READ.ME did not work, either. I've tinkered a lot with no succes.
- I have a debug log attached here.
- Sending you a share on my camera. If you have any issues with that, please let me know. There is nothing special about my network environment that should block you.
[home-assistant_2023-12-13T20-55-53.657Z.log](https://github.com/fuatakgun/eufy_security/files/13665753/home-assistant_2023-12-13T20-55-53.657Z.log)

**Comment by braddunlap** [comment]
I believe it is due to the fact that Eufy Doorbells do not support RTSP, so you need to install RTSP Simple Server Add On to support p2p cameras like the Eufy Doorbells. 

https://github.com/fuatakgun/rtsp_simple_server/tree/main

There wasn't instructions on how to install a 3rd party add on like this, but if you have done it before, you basically just copy the URL, go to Home Assistant Add Ons, go to Add on Store, click the 3 dots in the top right hand corner, and choose Repositories, paste the URL. After it downloads into Home Assistant, click on the repository and choose Install and it behaves like any other Add On.

Another thing to check is to make sure you set the streams to low and enable all notifications in the Eufy app like the instructions say to do.

**Comment by fuatakgun** [comment]
I have found the device in shared ones so looking at it now

**Comment by fuatakgun** [comment]
it is just working, please be sure that you have followed everything in README. You can see it below from my test environment.

![image](https://github.com/fuatakgun/eufy_security/assets/11085566/ebb96b56-3680-4a20-8043-9101eb5b0d12)
![image](https://github.com/fuatakgun/eufy_security/assets/11085566/b452a46e-566e-4ff0-bb98-8c69e9472626)
![image](https://github.com/fuatakgun/eufy_security/assets/11085566/a98b1a6c-f83e-4c80-8c08-5ef47507e3ed)

**Comment by fuatakgun** [comment]
In this test environment, I have latest eufy_security integration and webrtc integration from my fork (includes go2rtc), nothing more.
