### ISSUE TITLE
T8170 Sensors Missing / T8160 Camera Sensor Missing

### ISSUE THREAD

**Issue by Risotto8756** [fuatakgun/eufy_security#1108]
T8170. No sensors are available besides debug on/off. Can you add all the normal sensors for this newer camera of Eufy's.

Also, T8160 cameras. I see vehicle motion on/off switch but not vehicle detected sensor. Can you add that?

**Comment by Grzenioo** [comment]
With regards S340 / T8170, I did not see it yet on [the supported devices list](https://bropat.github.io/eufy-security-client/#/supported_devices).

@bropat Is it okay if I share my S340 with you on patrick.broetto+eu1@gmail.com? So that you could possibly add it in 1.8.0?

Or should I try to figure out what is missing to add the S340 by using [eufy-security-client](https://bropat.github.io/eufy-security-client)?

**Comment by bropat** [comment]
@grz-grz 

The device has already been implemented in eufy-security-client ([see here](https://github.com/bropat/eufy-security-client/pull/410)).
This device will also be supported in the next release of eufy-security-ws (1.8.0).

**Comment by fuatakgun** [comment]
great, thanks,

After new add-on version, please enable respective debug sensors, if they are disabled by default.
