### ISSUE TITLE
Host/Port is wrong

### ISSUE THREAD

**Issue by fescalante** [fuatakgun/eufy_security#1216]
Hi,

I am trying to put Eufy Security Add-on IP address and port (default values) but i receive the error: "Host/Port is wrong" and i cannot continue.

What can i do?

Thank you.

**Comment by clanic70** [comment]
Here exactly the same. Any idea how to fix it? Thanks

**Comment by clanic70** [comment]
Fixed! The problem was the related Add-On suddenly stopped. When I've restarted it manually, I was able to add Eufy integration into HA. ![image](https://github.com/user-attachments/assets/da6a317d-b634-4312-a641-d5bae87e2ef8)

![image](https://github.com/user-attachments/assets/cc71b6ea-f7e4-4896-899e-d5e8aaade3ba)

**Comment by fuatakgun** [comment]
there is nothing I can do here, it is basic setup needed so HA can communicate with add-on properly, if it is failing for some reason, I can do nothing,

If you have Home Assistant OS or Supervised installation, you should just set 127.0.0.1
