### ISSUE TITLE
live camera

### ISSUE THREAD

**Issue by jrspowers** [fuatakgun/eufy_security#214]
hello,

is it possible to add the function of the live camera so that you can always watch the images live now you only see the last image he saw little ?

**Comment by fuatakgun** [comment]
assuming your camera supports always streaming, you can use webrtc to watch it always inside home assistant, at the startup of home assistant, you should start RTSP livestream.

**Comment by jrspowers** [comment]
i have indoor cam ?

**Comment by jrspowers** [comment]
I can not fond rstp livestream on this camera ?

**Comment by boctok** [comment]
> I can not fond rstp livestream on this camera ?

Not all Eufy cameras support RTSP. If it does, the settings and link can usually be found in the app. For your camera, tap the gear icon and look under the storage tab. There will be another tab called (NAS)RTSP. This is where you can configure the stream and get the link. Some of the cameras will have the (NAS)RTSP tab under the main settings. If the camera doesn't have either of these, it doesn't support RTSP.

**Comment by jrspowers** [comment]
I can find that setting but can't get it set for this camera so I don't know what I'm doing wrong?

**Comment by fuatakgun** [comment]
I am personally having hard time to help you or at least understand the issue. If you want us to help you, give us all details what you have done so far and what is the specific issue.

**Comment by ishioni** [comment]
@fuatakgun I'll chime in here, because I don't understand it completely either. I'll preface that my camera does run rtsp, it's a T8410. It's enabled to have rtsp always on, and I can stream it properly when piping it via motioneye or ffmpeg. However, with your integration, I have to call eufy_security.start_rtsp_livestream which will make the camera given by the integration work for around 3 minutes, and then it idles back.

I'll also preface that I don't care about webrtc - while I understand it gives less lag, as far as I understand it will cause problems when I'm not on the same network as my camera. I don't really care about lag, but I care about it working consistently, so if HA handles it on it's own, with more delay, that's fine with me. I just want it to refresh the thumbnail consistently (it doesn't, but I understand that's a different bug) and that it plays when I click the picture element. I don't want to have hacks like call.service

**Comment by fuatakgun** [comment]
core streaming is fixed now (finally)
