### ISSUE TITLE
Doorbell chime volume select error on v2.2.2

### ISSUE THREAD

**Issue by dpomnean** [fuatakgun/eufy_security#220]
After updating the integration to the latest version v2.2.2, I started getting this error. Using the docker container version of bropat with 0.7.0. I've tried restarting the docker container and HA with same results.

Running core-2021.12.5

eufy_security - Doorbell - eufy_security_T8210XXXXXXX_chime_volume_select - select init missing value error - value: 26 - values_to_states: {'1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9', '10': '10', '11': '11', '12': '12', '13': '13', '14': '14', '15': '15', '16': '16', '17': '17', '18': '18', '19': '19', '20': '20', '21': '21', '22': '22', '23': '23', '24': '24', '25': '25'} - states_to_values: {'1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9', '10': '10', '11': '11', '12': '12', '13': '13', '14': '14', '15': '15', '16': '16', '17': '17', '18': '18', '19': '19', '20': '20', '21': '21', '22': '22', '23': '23', '24': '24', '25': '25'}

**Comment by ronaldt80** [comment]
Same error for me since 2.2.2.

eufy_security - Doorbell - eufy_security_T8210xxxxx_chime_volume_select - select init missing value error - value: 26 - values_to_states: {'1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9', '10': '10', '11': '11', '12': '12', '13': '13', '14': '14', '15': '15', '16': '16', '17': '17', '18': '18', '19': '19', '20': '20', '21': '21', '22': '22', '23': '23', '24': '24', '25': '25'} - states_to_values: {'1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9', '10': '10', '11': '11', '12': '12', '13': '13', '14': '14', '15': '15', '16': '16', '17': '17', '18': '18', '19': '19', '20': '20', '21': '21', '22': '22', '23': '23', '24': '24', '25': '25'}

**Comment by fuatakgun** [comment]
Please get latest version and update here

**Comment by stefanroelofs** [comment]
Error message is gone in latest version. 
And the chime volume entity is no longer 'Unknown':

![image](https://user-images.githubusercontent.com/37924749/150304614-7b2425ea-fc01-4d15-b3ed-23ddc29f18f9.png)

Thanks!

**Comment by dpomnean** [comment]
Can also confirm this fixed on my end after restarting bropat and HA containers.
