### ISSUE TITLE
Get alarm reset from Keypad state in HA

### ISSUE THREAD

**Issue by hipsi** [fuatakgun/eufy_security#233]
I have an external siren that I'd like to control from this integration with an automation. It works fine to activate the siren when the Homebase changes to a Triggered state, but this state doesn't stay in place until the alarm is reset, rather it appears to be momentary only when the trigger happens.  What this means is there's not really a way to reset the siren when the alarm is reset.

What would be great is a sensor for the Homebase to provide a notification when the alarm has been reset, either by app or keypad. This way there will be a trigger to respond to for deactivating the siren.

**Comment by fuatakgun** [comment]
Did you try triggering alarm with a duration?

**Comment by hipsi** [comment]
By calling the service? In which case do you mean to trigger the alarm
based on logic in HA as opposed to using the Eufy logic? I suppose that's
an option I didn't consider.

**Comment by fuatakgun** [comment]
you need to bring this discussion to eufy-security-client first as this information is not exposed to eufy_security information.

we are able to receive alarm triggered and cancelled, but if alarm goes off by itself, I do not receive any event for this.

**Comment by hipsi** [comment]
thank you I've opened a feature request on eufy-security-client

**Comment by hipsi** [comment]
Bropat has now enabled this in eufy-security-client

**Comment by samturner3** [comment]
@hipsi Do you have a link / instruction for this? Not sure what "feature request" you are referring to.
I too am trying to setup an external siren, via node red.
Has anyone done this and works??

It is impossible just by looking at the state changes of `alarm_control_panel.homebase`!!

### Results of my test:
#### Arming with exit delay:
_It goes into `armed_away` -> (exit delay expires) -> `triggered` -> `armed_away`_
![Screen Shot 2022-07-20 at 2 19 41 pm](https://user-images.githubusercontent.com/14887388/179896023-d69171e0-28fd-4901-975e-f0f5212a06b9.png)


#### Open door (trigger alarm) while armed:
It goes into `triggered` -> `armed_away`_ (even while alarm is sounding!) See timestamps.
![Screen Shot 2022-07-20 at 2 20 50 pm](https://user-images.githubusercontent.com/14887388/179896152-69c74d1b-d8e5-40a1-be6d-c0f726f258f5.png)


#### Disarm while in alarm (triggered):
_Note: It goes into `triggered` -> `disarmed`_
![Screen Shot 2022-07-20 at 2 21 02 pm](https://user-images.githubusercontent.com/14887388/179896166-44380461-b029-49d3-803a-0dfdbb0b65ea.png)


So I can't see a solution to reliably trigger the siren on intrusion and turn off on disarm, since when arming it goes from ``triggered` -> `armed_away``, EXACTLY like intrusion, (`triggered` -> `armed_away`)

One can not simply rely on the `triggered` state as it will go off for a second when arming, also only for a second on intruder when it switches back to `armed_away` instantly. 

Any solutions would be greatly appreciated.

**Comment by hipsi** [comment]
So my automation was set to take the triggered state as an input to toggle the siren off. I was then looking for a notification of alarm reset or change of mode to then toggle the siren off again.  This is the feature request I put in https://github.com/bropat/eufy-security-client/issues/105

**Comment by samturner3** [comment]
@hipsi ok, do you mind sharing how you implemented this on the home assistant level?

**Comment by hipsi** [comment]
@samturner3, there is no way currently as I understand it. Not until we get a different notification that identifies that the Homebase alarm has been reset or the mode has been changed (either from the keypad/app/or HA).
