### ISSUE TITLE
No Stations / Devices Found

### ISSUE THREAD

**Issue by hagepat** [fuatakgun/eufy_security#248]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
This is a new installation of Eufy 2K doorbell. In HA after the installation of Eufy Security I can't see any devices attached.

** What I already did **
Installed the APP on the phone created 1 main account with 2FA.
Added the HomeBase 2 and Battery Doorbell T8210 to my account.
After that I created a second account and shared my devices from the main account to the second account with "admin rights"
Send the invitation
Then I logged out the main account in the app and logged in with my second account. Accepted the invitation.
Checked that 2FA is disabled -> OK
Then in HA I installed Eufy Security with HACS (Follow instructions "https://github.com/fuatakgun/eufy_security")
Configured with username and password and country code: NL because I live in The Netherlands. See screenshot "SNAG-0000 27-Jan-22 7 50 41 PM"
I checked the log and you can see the output in "SNAG-0000 27-Jan-22 7 47 31 PM"
No devices or Stations found
Then I installed the RTSP Simple Server Add On
Installed the Eufy repository
Restart HA
Add integration
Entered localhost and port 3000
But of course no devices

Checked several post on the HA forum. And found this post "https://community.home-assistant.io/t/eufy-camera-integration/121758/1455" saw that "lvanagteren" has exactly the same problem. 
So I removed everything and started clean. But still the devices are not shown.

**To Reproduce**
Follow installation: https://github.com/fuatakgun/eufy_security

**Expected behavior**
See the Homebase and doorbell in the log and in the integration

**Screenshots**
Screenshots are added

**Hardware Information about Home Assistant
Raspberry Pi4 
HA Core: core-2021.12.10
HA SuperVisor: supervisor-2021.12.2
HA OS: Home Assistant OS 7.2
Eufy Security Add On: Current version: 0.7.0

**Hardware Information about Cameras
- HomeBase 2 and doorbell 2K battery powerd T8210
- Live Streaming Protocol: RTSP

**Additional context**
![SNAG-0000 27-Jan-22 7 47 31 PM](https://user-images.githubusercontent.com/86970871/151424057-c4840ac9-62fa-43f7-80db-aad8c687141e.png)
![SNAG-0000 27-Jan-22 7 50 41 PM](https://user-images.githubusercontent.com/86970871/151424486-6640939d-eb64-4427-a678-fbeb32f5fd80.png)

**Comment by AlanT0803** [comment]
I have a similar problem, but appears to be much worse.  The issue started following the update of the Eufy app which has changed the way the sharing works (or so it seems).
I receive the following when starting the add on:-

2022-01-28 09:28:58.938  INFO  Eufy Security server listening on port 3000 
2022-01-28 09:29:00.662  INFO  No stations found. 
2022-01-28 09:29:00.787  INFO  No devices found. 
2022-01-28 09:29:07.757  ERROR registerFid - Error: 
 RequestError  connect ECONNREFUSED 0.0.0.0:443
details:
{
  code: 'ECONNREFUSED',
  timings: undefined
}
error stack:
• index.js:1183 _makeRequest
    node_modules/got/dist/source/core/index.js:1183:19
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• index.js:334 <anonymous>
    node_modules/got/dist/source/core/index.js:334:17
2022-01-28 09:29:07.792  ERROR registerFid - Status return code not 200 
{
  status: undefined,
  statusText: undefined,
  data: undefined
}
2022-01-28 09:29:07.800  ERROR registerFid - Generic Error: 
 Error  FID registration failed with error: undefined
error stack:
• service.ts:87 registerFid
    node_modules/eufy-security-client/src/push/service.ts:87:23
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• service.ts:144 createPushCredentials
    node_modules/eufy-security-client/src/push/service.ts:144:16
• service.ts:506 _open
    node_modules/eufy-security-client/src/push/service.ts:506:32
• service.ts:565 open
    node_modules/eufy-security-client/src/push/service.ts:565:9
2022-01-28 09:29:07.808  ERROR Create push credentials Error: 
 Error  FID registration failed with error: Error: FID registration failed with error: undefined
error stack:
• service.ts:91 registerFid
    node_modules/eufy-security-client/src/push/service.ts:91:19
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• service.ts:144 createPushCredentials
    node_modules/eufy-security-client/src/push/service.ts:144:16
• service.ts:506 _open
    node_modules/eufy-security-client/src/push/service.ts:506:32
• service.ts:565 open
    node_modules/eufy-security-client/src/push/service.ts:565:9
2022-01-28 09:29:07.815  ERROR Push notifications are disabled, because the registration failed!
2022-01-28 09:29:07.814  INFO  Push notification connection closed 
2022-01-28 09:29:07.817  INFO  Retry to register/login for push notification in 5 seconds...

**Comment by fuatakgun** [comment]
Please follow here https://community.home-assistant.io/t/eufy-security-integration/318353/607?u=fuatakgun
