### ISSUE TITLE
A option not to run docker container for eufy-security-ws

### ISSUE THREAD

**Issue by asucrews** [fuatakgun/eufy_security#455]
**Is your feature request related to a problem? Please describe.**
Not related to a problem 

**Describe the solution you'd like**
Can there be a option added to not run the docker image eufy-security-ws? For my setup I got better proframace moving eufy-security-ws and rtsp-simple-server to a second host.  So I would like a way to turn off the eufy-security-ws docker image.

**Describe alternatives you've considered**
Not sure if there a alternative 

**Additional context**
Maybe I am one in million that has this need but it would be nice.

**Comment by fuatakgun** [comment]
You can see commands on readme how to run the add-ons (basically docker containers) standalone.

**Comment by asucrews** [comment]
Yes, and that what I am doing, what I was wondering if if three a way to tell the custom component not to load eufy-security-ws

**Comment by fuatakgun** [comment]
Component does not (cannot) run the docker container itself, container would ask user to supply the IP address of container. You can just give this a try, go through readme and see.

**Comment by asucrews** [comment]
I think I am not explain my self well. or just confused

**Comment by fuatakgun** [comment]
Integration is running inside home assistant system.

Eufy-security-ws is running as a docker container, wherever you want. Instead of docker container, add-on can be installed inside supervisor, but, from integration perspective, this doesn't matter. Rtsp server is also under this category. Integration is interested these docker containers ip addresses. It could be localhost or some other machine in your network or maybe a remote machine in cloud.

**Comment by asucrews** [comment]
Ahh I see thanks!
