### ISSUE TITLE
T8530 Smart Lock w/ video, code, and fingerprint access - and base station (T8021)

### ISSUE THREAD

**Issue by mwexcell** [fuatakgun/eufy_security#464]
I have a brand new T8530. Looks like it isn't supported. Can I help get support for this device added?

I've followed the instructions for setup. It is running the latest Firmware: 1.1.5.4 as of 9/17. 

I would be happy to share my Eufy home with you (this, and the base for it, are the only Eufy devices I currently have) according to the instructions on the readme if you will acknowledge that this is something that is doable. I can probably also help with debug from this end if there is anything you would like me to do to help.

Again, I haven't yet share the device with you. I will. Just let me know if and when you would like me to do that.

**Comment by fuatakgun** [comment]
Thanks for bringing this up. Can you check if eufy-security-client repository supports your device? If not, please work repository owner  @bropat and after he finishes it, let me know

**Comment by mwexcell** [comment]
Will do.

**Comment by jeremiezz** [comment]
Since I have add this device, my integration is not loading properly anymore, I have this error when I start it`Start Listening was not completed in timely manner`

Here the log from HA
`Logger: homeassistant.config_entries
Source: config_entries.py:1105
First occurred: 13:03:24 (1 occurrences)
Last logged: 13:03:24
Config entry 'localhost' for eufy_security integration not ready yet: Start Listening was not completed in timely manner; Retrying in background`

2nd error, it will maybe help you to add the lock to your integration
`Logger: custom_components.eufy_security
Source: custom_components/eufy_security/websocket.py:59
Integration: Eufy Security (documentation, issues)
First occurred: 13:01:28 (11 occurrences)
Last logged: 13:09:57
eufy_security - Exception - process_messages: 55 is not a valid DEVICE_TYPE - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 313, in on_message await self.process_get_device_properties_response( File "/config/custom_components/eufy_security/coordinator.py", line 260, in process_get_device_properties_response device.set_properties(properties) File "/config/custom_components/eufy_security/const.py", line 446, in set_properties type = DEVICE_TYPE(self.type_raw) File "/usr/local/lib/python3.10/enum.py", line 385, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.10/enum.py", line 710, in __new__ raise ve_exc ValueError: 55 is not a valid DEVICE_TYPE - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"get_device_properties","result":{"serialNumber":"T8530K1022290C64","properties":{"name":"Porte maison","model":"T8530","serialNumber":"T8530K1022290C64","type":55,"hardwareVersion":"P1","softwareVersion":"1.1.5.4","stationSerialNumber":"T8021P1122260DF9"}}}', extra='')`

**Comment by modogo2000** [comment]
Hello

I have exactly the same issue with the video smart lock: 

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/websocket.py:59
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 2:34:44 PM (28 occurrences)
Last logged: 3:13:26 PM

eufy_security - Exception - process_messages: 55 is not a valid DEVICE_TYPE - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 313, in on_message await self.process_get_device_properties_response( File "/config/custom_components/eufy_security/coordinator.py", line 260, in process_get_device_properties_response device.set_properties(properties) File "/config/custom_components/eufy_security/const.py", line 446, in set_properties type = DEVICE_TYPE(self.type_raw) File "/usr/local/lib/python3.10/enum.py", line 385, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.10/enum.py", line 710, in __new__ raise ve_exc ValueError: 55 is not a valid DEVICE_TYPE - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"get_device_properties","result":{"serialNumber":"T8530K1022290622","properties":{"name":"Front Door","model":"T8530","serialNumber":"T8530K1022290623","type":55,"hardwareVersion":"P1","softwareVersion":"1.1.5.4","stationSerialNumber":"T8021P10213012AB"}}}', extra='')

**Comment by KillaDreams** [comment]
#437

**Comment by MXKLZL** [comment]
Can we bypass the devices that are not yet supported so the other devices will load? thanks

**Comment by KillaDreams** [comment]
This is not my issu

**Comment by RyanAHolland** [comment]
I just installed the lock today and noticed the same thing. As soon as I shared the lock with my HA account, it broke the Integration. @MXKLZL suggestion of just unsharing restores my other devices.

I already have the TRUSTED_DEVICE_NAME set as @KillaDreams suggested, but I am getting the "Retrying setup: Start Listening was not completed in timely manner" error.

I checked the eufy_security_client repo and found a request to add this lock here: https://github.com/bropat/eufy-security-client/issues/220

What is interesting is the Home Assistant Add-On loads just fine; it is just the integration that breaks.

Hopefully, we can get this added, as I already really like this lock.

Let me know what I can do to help!

**Comment by the-despised** [comment]
Same issue here.

`This error originated from a custom integration.

Logger: custom_components.eufy_security
Source: custom_components/eufy_security/websocket.py:59
Integration: Eufy Security (documentation, issues)
First occurred: 12:35:58 AM (575 occurrences)
Last logged: 3:12:50 PM

eufy_security - Exception - process_messages: 55 is not a valid DEVICE_TYPE - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 313, in on_message await self.process_get_device_properties_response( File "/config/custom_components/eufy_security/coordinator.py", line 258, in process_get_device_properties_response device.set_properties(properties) File "/config/custom_components/eufy_security/const.py", line 452, in set_properties type = DEVICE_TYPE(self.type_raw) File "/usr/local/lib/python3.10/enum.py", line 385, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.10/enum.py", line 710, in __new__ raise ve_exc ValueError: 55 is not a valid DEVICE_TYPE - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"get_device_properties","result":{"serialNumber":"T8530K1022290E64","properties":{"name":"Front Door","model":"T8530","serialNumber":"T8530K1022290E64","type":55,"hardwareVersion":"P1","softwareVersion":"1.1.8.2","stationSerialNumber":"T8021P11222621CE"}}}', extra='')`

**Comment by fuatakgun** [comment]
please try with alpha release v5.x.x and let me know

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/591

**Comment by xbmcnut** [comment]
I have just configured all of the necessary components for the HA add-on and despite it connecting to both the bridge and the lock, I'm not seeing anything useful in the lock section. Have I jumped the gun with support for the 8530?

![image](https://user-images.githubusercontent.com/1492137/210935775-b0925576-f64a-4b27-9045-2eb461fbe9d0.png)

Eufy Security Add-on, Current version: 1.3.0
Eufy Security v6.1.0 via HACS

P.S Had to change port on Eufy Security Add-on to 3030 as Z-Wave JS UI was already using 3000

**Comment by fuatakgun** [comment]
Why did you assume so?

It was not captured on supported device list.

Check readme.

**Comment by billdwhite** [comment]
@fuatakgun:  Ok sounds good;  I think the confusion is because this issue was closed so we might have concluded the support was implemented.  I'll keep an eye out for that to appear on the supported device list.  Thanks so much for your hard work on this valuable project.  :)

**Comment by fuatakgun** [comment]
No no, you have to work with @bropat over eufy-security-client repository, share your device with him so he can add the support.

Without access to new devices, he would not do it. That is because i am always referring to readme and links there because you would find this out.

When device support is added, he will release a new version and so do I

**Comment by xbmcnut** [comment]
Thanks for the clarification. For me, my confusion came from the release notes that showed the 8530 mentioned in the code and it's tricky for us non-coders to understand all the components required to make this work. I'll keep an eye on the supported devices from now on for my main source of info. Many thanks for your great work. 

![image](https://user-images.githubusercontent.com/1492137/211117995-f7a867b5-dab6-4700-8608-b666ad37d003.png)
