### ISSUE TITLE
retrying setup exception host/port is not reachable localhost 3000

### ISSUE THREAD

**Issue by FlouHappy** [fuatakgun/eufy_security#490]
I am tryinf to add my eufy WIFI smart lock (T8520) to Home assistant for a while (months) and I still have the same wall. I always receive this message (Retrying setup: Exception: Host/port is not reachable localhost 3000!). But worse now, Eufy_Security_addon doesn't stay up. I have to start it manually everytime. As it shutdown1 or 2 minutes after I start it. Here is what I have in the log
![image](https://user-images.githubusercontent.com/42975832/196092765-47c4ab98-5b76-45c9-927b-d6f0d29a12ce.png)
Any help @fuatakgun ?
![image](https://user-images.githubusercontent.com/42975832/196092885-fe4bdbed-d196-41ab-92fa-859857c46a25.png)
![image](https://user-images.githubusercontent.com/42975832/196092888-3877b9dc-4d87-4e4b-a3e4-6b1dbc214e34.png)

Thank you

**Comment by davidjac** [comment]
Same here

**Comment by urtziDV** [comment]
Same problem....

**Comment by Kri72** [comment]
Hello.. Same here!

**Comment by dundiffrunt** [comment]
Same here!

**Comment by urtziDV** [comment]
I have managed to solve it by accessing Portainer and forcing the Eufy service to start, since it appeared as stopped. Later I have activated the automatic restart in case of error.
I have also taken advantage of it and have done "apt update" and "apt upgrade" through Putty. I have also updated Portainer to v 2.15.1. Finally I have updated Home Assistant, and Eufy is already working.

**Comment by dundiffrunt** [comment]
I can't replicate this because my HA is running on a Pi. So no Portainer to update here....

**Comment by Kri72** [comment]
Hello..it is now working ok again for me.. Probably because of the last update of one of the home assistant module..

**Comment by fuatakgun** [comment]
@FlouHappy  this is because of my poor error messaging `retrying setup exception host/port is not reachable localhost 3000`.

As you have posted from add-on logs, add-on is not able to initialize properly and integration cannot be setup.

Please reach out to @bropat over here https://github.com/bropat/eufy-security-ws

Device seems to be supported since `1.6.0 (2022-02-05)` but there seems to be some more problems.
