### ISSUE TITLE
RTSP Streaming Issues ???

### ISSUE THREAD

**Issue by fuatakgun** [fuatakgun/eufy_security#593]
1. https://github.com/fuatakgun/eufy_security/issues/568

**Comment by maddogrvo** [comment]
I have this problem too with the eufycam 3, seems the turn_on service is not working correctly, if i open the camera via the eufy app at night it turns on the light automatically. However i don`t see that happening when i try it via home-assistant. Keeps saying 404 not found.

Is it possible to use p2p streaming so i can turn off the rtsp stream, i ask this because the camera`s are 4k but when you turn on rtsp only full hd recordings are available :(?

**Comment by fuatakgun** [comment]
what do you mean with `this problem too`?
You mention about automation turning on light or non functional RTSP issue. Please raise a separate issue and share your device with me.
you can use P2P streaming even you have RTSP on, but you have to call start_p2p_livesteam servie.

**Comment by maddogrvo** [comment]
Ahh sorry i meant that i am unable to capture the RTSP video stream / have no video stream. With turning on the light i meant as soon as a stream is opened for the camera, it automatically turns on the light by itself, thats why i thought that turn_on was not working correctly, if i try to turn on the camera with the action below i do not see the same behaviour

      tap_action:
        action: call-service
        service: camera.turn_on
        target:
          entity_id: camera.zijdeur

For the start_p2p_livestream i get an error from home-assistant that the service does not exist, i used the same code as above and replaced the service: camera.turn_on with service: camera.start_p2p_livestream

**Comment by fuatakgun** [comment]
please switch to alpha version

**Comment by maddogrvo** [comment]
Done, seems to work now, i am able to see the livestreams, thnx for all your work
