### ISSUE TITLE
Arm away , disarm and arm home not  available in node red  

### ISSUE THREAD

**Issue by kibrom631** [fuatakgun/eufy_security#749]
I use node red for home automation and  arm_home 
arm_away  and disarm  are not available. Please check  the screenshot attached for more information . i am getting all of them except I could not call a service for the listed three service above.

![Screen Shot 2023-02-22 at 10 51 21 AM](https://user-images.githubusercontent.com/113874686/220713616-41d8512f-39c6-4ea7-b12a-534eeea5b706.png)

**Comment by kibrom631** [comment]
it is not actually in node red only, it is also in home assistant.

**Comment by kvanbiesen** [comment]
IS it possible to open this again @kibrom631 has a point

while the controls are availble for the control panel, the settings are not available in the eufy_security.
Hence we cant set the Alarm modus of for example the flood light to away or disarm it. For the control panel its working as intended. For standalone devices, only a few modes we can pick

The settings work tru the HA panel, but cant be changed with automations. 

TRied set_options; set_value and everything;

**Comment by fuatakgun** [comment]
@kvanbiesen , please can you elaborate more? I am lost

**Comment by fuatakgun** [comment]
For away and disarm, you can use alarm_control_panel services.

Custom ones are specific to integration and they are part of eufy_security domain.

**Comment by kvanbiesen** [comment]
Doesn't work, the alarm control panel services don't work on the
floodlight.

The eufy security ones do work.
Well it's not a big issue, I currently change the setting with set_option .
That works. But seems weird that you can put it to geofencing/custom but
not away or disarm it that way. But as I said...minor issue as it can be
worked around


But here the control panel services , don't work on the floodlights

**Comment by fuatakgun** [comment]
Then we should discuss why they are not working rather than moving services under eufy security domain.

Even though if i would move them, they would still not work because i will use the same code nothing different.

**Comment by kvanbiesen** [comment]
It's not really moving, as you see in the first sceeenshot, the actions are
already under eufy_security, just not all of them

Alarm_arm_custom1, 2,3, geofence, schedule, .... They all work on the
floodlight and are already integrated. It's just missing a couple ones.
Away and disarm most importantly.


Making control panel work seems weird, cause it has nothing to do with
control panel...for example if you only have a floodlight 2k...does this
domain even shows up when you don't have an eufy alarm system?

**Comment by fuatakgun** [comment]
I really do not understand the issue here, i am not saying that you are not telling the truth.

From an inheritance perspective, there is no reason for me to setup these same services under eufy security domain because I am inheriting these from alarm control panel.

What is a camera? A device which generates motion/person sensors, last event and probably a stream.

What is an alarm control panel? A device which you can alarm/disalarm/geofence etc.

Any standalone camera is acting as both camera and alarm control panel.

So, if some of these services exist in parent domains, i would just reuse them. If these services are explicit for eufy security, i would implement them under the eufy security domain.

If we are done why we need a camera or ala control panel and you have a problem to switch between states using respective domains, create an issue/bug for it. But i don't see a reason to move them.
