### ISSUE TITLE
Setup Help : Stream not working 

### ISSUE THREAD

**Issue by ste-sanjaysingh** [fuatakgun/eufy_security#790]
Please check existing (open or closed) issues before creating a new one. (https://github.com/fuatakgun/eufy_security/issues?q=is%3Aissue+)

If this is not an issue, you can use `Discussions` (https://github.com/fuatakgun/eufy_security/discussions) section.

**Describe the bug**

**To reproduce** 
![Capture](https://user-images.githubusercontent.com/52054502/235758581-b5e54ff0-6a1d-45bb-900b-dcc0222714de.JPG)

4. See the error

**Expected behavior**
![Capture](https://user-images.githubusercontent.com/52054502/235758945-64df511f-1f2f-4ce9-a9d2-b8052cd169ed.JPG)

**Additional information**

Go to Settings -> System -> Repairs -> Click on 3 dots (...) -> System Information and get Version and Installation Type to the below fields;
- Home Assistant Installation Type (OS - Supervised - Core):  OS
- Home Assistant Core Version: 2023.4.6
- Eufy Security Add-on Version: Latest
- Eufy Security Integration Version: Latest

Hardware Information;
- Camera Model: 3C

- Live Streaming Protocol (RTSP/P2P): 
Both

- Debug Logs from Home Assistant (https://github.com/fuatakgun/eufy_security/discussions/624)
- 

- Logs from Eufy Security Add-on (either from the Add-ons page of Home Assistant or Docker output):

- Would you share your device with me in case further debugging is required? (Yes/No):  Yes

Hi, I have researched and researched there is not any single video or even updated article available on using this integration, I have tried all the instructions and using Eufy cam 3 but after following all the steps I was able to get the cameras ad base station discovered and added to the HA dashboard but unfortunately, nothing streams out of it, I tried RTSP and all but still no luck

Add any other context about the problem goes here.

**Comment by buzurk26** [comment]
Mines doing the same for months now, no fix in sight :(

**Comment by troyhatchard** [comment]
I have the same thing. I'm sure it has to do with incorrect setup, but I can't find anywhere I deviated from the instrucitons.

**Comment by troyhatchard** [comment]
Ok. I managed to get something working. In the "device info" for each camera, I stopped the P2P stream, enabled the RTSP stream, and started the RTSP stream. This got the camera stream working from my dashboard. But then I turned the cameras off and on again. The streams did not work this time. Not sure what's going on.

**Comment by c0nt4x** [comment]
I'm showing the same screen. I have just installed the camera and can't get a picture in the dashboard card.

I checked the integration and it is showing all the device info, so I've confirmed it connected to the integration but for some reason it is showing the device as 'Armed Away' when the Eufy mobile app is showing it is in 'Home' mode. The device info correctly shows detection but still no image on the card. I've rebooted the camera and HA, used the example in this repo for the conditional card code and changed the entity name to my camera but still no image.

**Comment by TYZZ-HA** [comment]
Hi folks,

I thought that the problem described in the thread was specific to my crapy network, but i guess it's not.

I've managed to time-ish the timeouts and it seems to happen at 5 minutes... ish. The RTSP stream needs to be restarted for the camera to work, as stated above, in the device info view. 
My "solution" to the problem was to create a timed automation in Node-Red that restarts the stream every 4 minutes. Honestly, i hate this solution cause it keeps the stream up and running more or less all the time, which i bet creates some memory leaks, but it works. I have the stream up for many hours a day via HomeKit and it works flawlessly.

It would be nice if the problem could be solved within the integration, so we don't have to restart the stream manually. Or at least to know the reason to the problem :)

Cheers,

**Comment by c0nt4x** [comment]
I now seem to have a stable, permanent video image. Not sure what I did to resolve it as I've done a lot of playing about with settings but I did, at one point ,uninstall all the related integrations and add-ons then reinstalled and re-setup and all seems to be working now for 2 days.
One point I did realise was that the live stream url is not anything like the examples and I found it in the Eufy native app and that made the difference...I think.

**Comment by ste-sanjaysingh** [comment]
That’s really amazing to hear that it is completely working for you with no trouble. I eventually gave up but I think I wasn’t even close to what you guys might have done to troubleshoot. If you be so kind to creat step by step guide or a video I know alot of us who are trying to set this up would thanks a million to you. The creators of these integration don’t seem to care that much about this.

**Comment by TYZZ-HA** [comment]
> 

Wow! I'm really happy that you've seemed to make it work!

To bad though that you're unsure about the actual "fix", but i am wondering if you can elaborate a bit on the URL difference?
Do you mean that the RTSP Stream URL in the device info was different from the one in the Eufy APP -> RTSP settings? I am asking because that URL is spot on the same in both places at me.

**Comment by c0nt4x** [comment]
I didn't explain properly in my previous post. The URL I was referring to is the one in the WebRTC Lovelace custom card. I was entering, for example, `rtsp://198.162.1.58:554/...`but then realised it had to be `rtsp://XXXXXX:XXXXX/...` and found that URL in the native Eufy app.
But, I think my initial issue was I didn't take any notice of the instruction to create a second account and to share that and use that log in to be able to access the camera. When I did that, and entered the correct URL all was good.
I was so confused because of having to use 2 integrations and 2 add-ons, with so many port numbers and URL's it got confusing, but all good now and I'm waiting for another Eufy camera and doorbell to be delivered and then I can add them to HA, so thanks for your work on this.

**Comment by c0nt4x** [comment]
> Wow! I'm really happy that you've seemed to make it work!
> 
> To bad though that you're unsure about the actual "fix", but i am wondering if you can elaborate a bit on the URL difference? Do you mean that the RTSP Stream URL in the device info was different from the one in the Eufy APP -> RTSP settings? I am asking because that URL is spot on the same in both places at me.

One thing I am stuck on though, is getting my Eufy non-RTSP cameras and doorbell included in WebRTC. What format URL do I use? The RTSP camera uses a format like `rtsp://xxxxxxxxx:xxxxxxxxx@192.168.1.144/live0`which is found in the Eufy native app and this works fine. But for the non-RTSP cameras, the Eufy integration show the RTSP URL in the format `rtsp://localhost:8554/T8210PXXXXXXXX` but this causes errors in the dashboard card.
Do I need to enter something else as the URL for non-RTSP cameras or should the above work?

**Comment by fuatakgun** [comment]
instead of putting the url into webrtc card, why dont you set the camera entity on respective card, it will pick the URL automatically

**Comment by BrandingYou** [comment]
Having the same issue. Where in the native eufy app can i find the URL?

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/issues/647
