### ISSUE TITLE
Eufy off/disarmed

### ISSUE THREAD

**Issue by onelius** [fuatakgun/eufy_security#890]
**Describe the bug**
The alarm shows as off in home assistant instead off disarmed as before.

**Expected behavior**
Off in the eufy app and on eufy keypad should show as disarmed in home assistant.

Disarmed in home assistant should place eufy app and keypad in off mode.

**Additional information**
In version 6.2 it was working as expected, when updated to lates version it changed.

**Comment by fuatakgun** [comment]
@kvanbiesen , can you chime in so we can all discuss best way forward.

**Comment by kvanbiesen** [comment]
In my opinion, nothing. Cause off is off and disarmed is disarmed. Since
both states exist in the eufy app, imho both states should exist in HA.

It's the opposite of https://github.com/fuatakgun/eufy_security/issues/840
Which is in my option the more valid one.

These user should adapt his automations (if he has any) to take in both
both states...

If he wants to see disarmed, he should set his alarm to disarmed.
Technically we could say states away, geofence, schedule, custom1 .... As
just armed but we don't do that either so yeah off stays.

(Not because I choose, but because it makes more sense, to have the actual
state in there)
